# Generated by Django 3.2.9 on 2021-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211111_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='route',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
