# Generated by Django 3.2.9 on 2021-11-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='url',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
